# Generated by Django 5.2.12 on 2026-04-02 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="verse_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="API Bible verse reference, e.g. 'JHN.3.16'.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="verse_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="API Bible verse reference for API Bible highlights.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="verse_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="API Bible verse reference for API Bible notes.",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="segregatedpagecomment",
            index=models.Index(
                fields=["page", "-created_at"], name="bible_segre_page_id_afe73a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="segregatedpagecomment",
            index=models.Index(fields=["user"], name="bible_segre_user_id_c0c1bf_idx"),
        ),
        migrations.AddIndex(
            model_name="segregatedpagelike",
            index=models.Index(fields=["page"], name="bible_segre_page_id_b71b79_idx"),
        ),
        migrations.AddIndex(
            model_name="translatedpagecache",
            index=models.Index(
                fields=["page", "language_code"], name="bible_trans_page_id_4edbbe_idx"
            ),
        ),
    ]
