# Generated by Django 5.2.12 on 2026-03-15 18:01

import apps.accounts.models
import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Immutable primary identifier. Cannot be changed after registration.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("prefer_not_to_say", "Prefer Not to Say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="en",
                        help_text="ISO 639-1 language code (e.g., en, es, fr, pt, hi, ar, sw).",
                        max_length=10,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        default="",
                        upload_to=apps.accounts.models.profile_photo_upload_path,
                    ),
                ),
                (
                    "bio",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        validators=[apps.common.validators.validate_bio_length],
                    ),
                ),
                (
                    "account_visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("hide_followers_list", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="BlockRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "block relationship",
                "verbose_name_plural": "block relationships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FollowRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("pending", "Pending")],
                        default="accepted",
                        max_length=10,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "follow relationship",
                "verbose_name_plural": "follow relationships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("hashed_code", models.CharField(max_length=128)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP token",
                "verbose_name_plural": "OTP tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["country"], name="accounts_us_country_fe12a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["preferred_language"], name="accounts_us_preferr_2564fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_of_birth"], name="accounts_us_date_of_b40948_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockrelationship",
            index=models.Index(
                fields=["blocker"], name="accounts_bl_blocker_f8b729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockrelationship",
            index=models.Index(
                fields=["blocked"], name="accounts_bl_blocked_d34d39_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="blockrelationship",
            constraint=models.UniqueConstraint(
                fields=("blocker", "blocked"), name="unique_block_relationship"
            ),
        ),
        migrations.AddConstraint(
            model_name="blockrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("blocker", models.F("blocked")), _negated=True),
                name="prevent_self_block",
            ),
        ),
        migrations.AddIndex(
            model_name="followrelationship",
            index=models.Index(
                fields=["follower", "status"], name="accounts_fo_followe_ecff01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followrelationship",
            index=models.Index(
                fields=["following", "status"], name="accounts_fo_followi_fc8821_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="followrelationship",
            constraint=models.UniqueConstraint(
                fields=("follower", "following"), name="unique_follow_relationship"
            ),
        ),
        migrations.AddConstraint(
            model_name="followrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("follower", models.F("following")), _negated=True),
                name="prevent_self_follow",
            ),
        ),
        migrations.AddIndex(
            model_name="otptoken",
            index=models.Index(
                fields=["user", "purpose", "used"],
                name="accounts_ot_user_id_dc12b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otptoken",
            index=models.Index(
                fields=["expires_at"], name="accounts_ot_expires_4348db_idx"
            ),
        ),
    ]
