# Generated by Django 5.2.12 on 2026-04-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_privacy_and_follow_status"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="followrelationship",
            new_name="accounts_fo_followe_4d4e45_idx",
            old_name="accounts_fo_followe_idx",
        ),
        migrations.RenameIndex(
            model_name="followrelationship",
            new_name="accounts_fo_followi_953086_idx",
            old_name="accounts_fo_followi_idx",
        ),
        migrations.AddIndex(
            model_name="otptoken",
            index=models.Index(
                fields=["user", "purpose", "used", "-created_at"],
                name="accounts_ot_user_id_92d3c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_email_verified"], name="accounts_us_is_emai_fb6e2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_login"], name="accounts_us_last_lo_42da58_idx"
            ),
        ),
    ]
