# Generated by Django 5.2.12 on 2026-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_rename_accounts_fo_followe_idx_accounts_fo_followe_4d4e45_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="post_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="prayer_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
