# Generated by Django 5.2.12 on 2026-04-02 18:28

from django.db import migrations


def backfill_user_counters(apps, schema_editor):
    """Backfill denormalized counters from existing data."""
    User = apps.get_model("accounts", "User")
    FollowRelationship = apps.get_model("accounts", "FollowRelationship")
    Post = apps.get_model("social", "Post")
    Prayer = apps.get_model("social", "Prayer")

    for user in User.objects.all().iterator(chunk_size=500):
        User.objects.filter(pk=user.pk).update(
            follower_count=FollowRelationship.objects.filter(
                following_id=user.pk
            ).count(),
            following_count=FollowRelationship.objects.filter(
                follower_id=user.pk
            ).count(),
            post_count=Post.objects.filter(author_id=user.pk).count(),
            prayer_count=Prayer.objects.filter(author_id=user.pk).count(),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_follower_count_user_following_count_and_more"),
        ("social", "0003_post_comment_count_post_reaction_count_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_user_counters, migrations.RunPython.noop),
    ]
