# Generated by Django 5.2.12 on 2026-03-15 18:01

import apps.common.storage_backends
import apps.shop.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(
                        storage=apps.common.storage_backends.PublicMediaStorage(),
                        upload_to=apps.shop.models.product_cover_upload_path,
                    ),
                ),
                (
                    "product_file",
                    models.FileField(
                        help_text="The downloadable file (PDF, ZIP, MP3, etc.). Served via pre-signed URLs.",
                        storage=apps.common.storage_backends.PrivateMediaStorage(),
                        upload_to=apps.shop.models.product_file_upload_path,
                    ),
                ),
                (
                    "price_tier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Maps to the IAP product ID for paid products.",
                        max_length=50,
                    ),
                ),
                ("is_free", models.BooleanField(db_index=True, default=False)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "apple_product_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "google_product_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="shop_produc_categor_52ee12_idx",
                    ),
                    models.Index(
                        fields=["is_free", "is_active"],
                        name="shop_produc_is_free_796446_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")], max_length=10
                    ),
                ),
                (
                    "receipt_data",
                    models.TextField(
                        help_text="Raw receipt data from Apple/Google for server-side validation."
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("is_validated", models.BooleanField(db_index=True, default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase",
                "verbose_name_plural": "purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="shop.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for free product downloads.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downloads",
                        to="shop.purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "download",
                "verbose_name_plural": "downloads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["user", "-created_at"], name="shop_purcha_user_id_6d8e3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["product"], name="shop_purcha_product_54b8a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["user", "-created_at"], name="shop_downlo_user_id_34c4a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["product"], name="shop_downlo_product_0b5e72_idx"
            ),
        ),
    ]
