# Generated by Django 5.2.12 on 2026-04-02 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["user", "product"], name="shop_downlo_user_id_97b2f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["user", "product"], name="shop_purcha_user_id_52c638_idx"
            ),
        ),
    ]
