# Generated by Django 5.2.12 on 2026-04-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_download_shop_downlo_user_id_97b2f2_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price in INR for web (Razorpay) purchases. Null for IAP-only products.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="razorpay_order_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Razorpay order ID for web purchases.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="razorpay_payment_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Razorpay payment ID for web purchases.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="platform",
            field=models.CharField(
                choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="receipt_data",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Raw receipt data from Apple/Google for server-side validation.",
            ),
        ),
    ]
