# Generated by Django 5.2.12 on 2026-04-04 18:09

from decimal import Decimal
from django.db import migrations


def set_prices(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    # Set ₹10 for all paid products (tier_1 and tier_2)
    Product.objects.filter(is_free=False).update(price=Decimal("10.00"))


def unset_prices(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    Product.objects.filter(is_free=False).update(price=None)


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_product_price_purchase_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.RunPython(set_prices, unset_prices),
    ]
