# Generated by Django 5.2.12 on 2026-03-15 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoostAnalyticSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Engagement rate as a percentage (e.g., 3.50 = 3.5%).', max_digits=5)),
                ('link_clicks', models.PositiveIntegerField(default=0)),
                ('profile_visits', models.PositiveIntegerField(default=0)),
                ('snapshot_date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'boost analytic snapshot',
                'verbose_name_plural': 'boost analytic snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='PostBoost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tier', models.CharField(help_text='Maps to the IAP product ID for the boost tier.', max_length=50)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'post boost',
                'verbose_name_plural': 'post boosts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.UUIDField()),
            ],
            options={
                'verbose_name': 'post view',
                'verbose_name_plural': 'post views',
                'ordering': ['-created_at'],
            },
        ),
    ]
