# Generated by Django 5.2.12 on 2026-03-15 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postboost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='social.post'),
        ),
        migrations.AddField(
            model_name='postboost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_boosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boostanalyticsnapshot',
            name='boost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='analytics.postboost'),
        ),
        migrations.AddField(
            model_name='postview',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'social'), ('model__in', ['post', 'prayer'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='postview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='postboost',
            index=models.Index(fields=['post', 'is_active'], name='analytics_p_post_id_6efe65_idx'),
        ),
        migrations.AddIndex(
            model_name='postboost',
            index=models.Index(fields=['user'], name='analytics_p_user_id_c7775d_idx'),
        ),
        migrations.AddIndex(
            model_name='postboost',
            index=models.Index(fields=['is_active', 'expires_at'], name='analytics_p_is_acti_1c5fdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='boostanalyticsnapshot',
            constraint=models.UniqueConstraint(fields=('boost', 'snapshot_date'), name='unique_snapshot_per_boost_per_day'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['content_type', 'object_id'], name='analytics_p_content_fa22ef_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['viewer'], name='analytics_p_viewer__e2a643_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['viewer', 'content_type', 'object_id', 'created_at'], name='analytics_p_viewer__f37495_idx'),
        ),
    ]
