# Generated by Django 5.2.12 on 2026-03-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_postview_view_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postview',
            new_name='analytics_p_content_353541_idx',
            old_name='analytics_p_content_vt_idx',
        ),
    ]
