# Generated by Django 5.2.12 on 2026-04-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "analytics",
            "0004_rename_analytics_p_content_vt_idx_analytics_p_content_353541_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="boostanalyticsnapshot",
            index=models.Index(
                fields=["boost", "-snapshot_date"],
                name="analytics_b_boost_i_f416a3_idx",
            ),
        ),
    ]
