# Generated by Django 5.2.12 on 2026-04-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_boostanalyticsnapshot_analytics_b_boost_i_f416a3_idx"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostViewDailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("summary_date", models.DateField()),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("unique_viewers", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "post view daily summary",
                "verbose_name_plural": "post view daily summaries",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "summary_date"],
                        name="analytics_p_content_404dbc_idx",
                    ),
                    models.Index(
                        fields=["summary_date"], name="analytics_p_summary_44460c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "summary_date"),
                        name="unique_view_summary_per_content_per_day",
                    )
                ],
            },
        ),
    ]
