# Generated by Django 5.2.12 on 2026-04-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_postviewdailysummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="postboost",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price in INR for web (Razorpay) boost purchases.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="postboost",
            name="razorpay_order_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Razorpay order ID for web boost purchases.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="postboost",
            name="razorpay_payment_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Razorpay payment ID for web boost purchases.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="postboost",
            name="platform",
            field=models.CharField(
                choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                max_length=10,
            ),
        ),
    ]
