# Generated by Django 5.2.12 on 2026-04-02 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reaction",
            index=models.Index(
                fields=["user", "content_type", "object_id"],
                name="social_reac_user_id_87d13e_idx",
            ),
        ),
    ]
