# Generated by Django 5.2.12 on 2026-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_reaction_social_reac_user_id_87d13e_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="reaction_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayer",
            name="comment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prayer",
            name="reaction_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
