# Generated by Django 5.2.12 on 2026-04-02 18:28

from django.db import migrations


def backfill_content_counters(apps, schema_editor):
    """Backfill reaction_count and comment_count for existing Posts and Prayers."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    Reaction = apps.get_model("social", "Reaction")
    Comment = apps.get_model("social", "Comment")
    Post = apps.get_model("social", "Post")
    Prayer = apps.get_model("social", "Prayer")

    post_ct = ContentType.objects.get_for_model(Post)
    for post in Post.objects.all().iterator(chunk_size=500):
        Post.objects.filter(pk=post.pk).update(
            reaction_count=Reaction.objects.filter(
                content_type=post_ct, object_id=post.pk
            ).count(),
            comment_count=Comment.objects.filter(
                content_type=post_ct, object_id=post.pk
            ).count(),
        )

    prayer_ct = ContentType.objects.get_for_model(Prayer)
    for prayer in Prayer.objects.all().iterator(chunk_size=500):
        Prayer.objects.filter(pk=prayer.pk).update(
            reaction_count=Reaction.objects.filter(
                content_type=prayer_ct, object_id=prayer.pk
            ).count(),
            comment_count=Comment.objects.filter(
                content_type=prayer_ct, object_id=prayer.pk
            ).count(),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_post_comment_count_post_reaction_count_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_content_counters, migrations.RunPython.noop),
    ]
